// Generated by scripts/sync-form-content.ts — DO NOT EDIT.
// Verbatim content of the live "Support Near You" Google Form:
// https://docs.google.com/forms/d/e/1FAIpQLSfWRp9OXEbfmIJtW4E_nEYwkXVUts0sfFxtkvhVOtSbCBTuFw/viewform
// Regenerate with `bun run form:sync`; verify with `bun run form:check`.
// Strings are byte-exact apart from trimmed trailing/outer whitespace — the
// typos, double spaces, en dashes and curly quotes are the form's own.
import type {
  COMPLETED_BY_OPTIONS,
  FUNDING_OPTIONS,
  HEARD_ABOUT_OPTIONS,
  SERVICES,
} from "./types";

export type FieldKey =
  | "completedBy"
  | "confirmConsent"
  | "confirmAssess"
  | "confirmCoordinate"
  | "confirmCommunicate"
  | "services"
  | "funding"
  | "name"
  | "email"
  | "phone"
  | "headline"
  | "locality"
  | "personSought"
  | "circumstances"
  | "pets"
  | "petDetails"
  | "schedule"
  | "consentWcn"
  | "consentOther"
  | "heardAbout"
  | "newsletter"
  | "disclaimerRead"
  | "accurateInfo";

export interface FormOption {
  readonly label: string;
  readonly isOther?: true;
}

export interface NoteItem {
  readonly kind: "note";
  readonly title: string;
  readonly description?: string;
}

export interface TextQuestion {
  readonly kind: "short" | "paragraph";
  readonly key: FieldKey;
  readonly entryId: number;
  readonly title: string;
  readonly description?: string;
  readonly required: boolean;
  readonly maxLength?: number;
}

export interface ChoiceQuestion {
  readonly kind: "radio" | "checkboxes";
  readonly key: FieldKey;
  readonly entryId: number;
  readonly title: string;
  readonly description?: string;
  readonly required: boolean;
  readonly options: readonly FormOption[];
}

export type FormQuestion = TextQuestion | ChoiceQuestion;
export type FormItem = NoteItem | FormQuestion;

export type SectionId = "screening" | "needs" | "about" | "consent" | "touch" | "disclaimer";

export interface FormSection {
  readonly id: SectionId;
  readonly pillLabel: string;
  readonly title: string;
  readonly description?: string;
  readonly items: readonly FormItem[];
}

export interface FormMeta {
  readonly title: string;
  readonly description: string;
  readonly confirmationMessage: string;
  readonly rejection: { readonly title: string; readonly description: string };
}

export const FORM_META: FormMeta = {
  title: "Support Near You – Find a Micro-provider",
  description: "This simple and easy to use tool will help you find local support in Wells, Shepton Mallet and surrounding villages by matching you with a Micro-provider. Micro-providers are local self employed-carers who offer a range of care and support services to help people at home or in the community.\nWhen you fill in this form we will share your details with Wells Community Network approved Micro-providers near you. We will then contact you with details of all the Micro-providers who are available to support you, leaving you to choose the right support for you.\nWhen you submit this form, it will not automatically collect your details like name and email address unless you provide it yourself.",
  confirmationMessage: "Thank you for applying for support, we will process your request within three working days.   If you have any other enquiries please contact the WCN Helpline 01749 467079",
  rejection: {
    title: "Micro-providers may not be the right option at this time",
    description: "Thank you for your interest.\nBased on your answers, Micro-providers may not be the most suitable option, as this model requires individuals or families to manage and co-ordinate care independently.\nYou may wish to explore CQC-regulated care providers or speak with your local council for alternative support options.\nIf you feel this statement is not accurate, and you wish to proceed please email us on wcnmicroproviders@gmail.com",
  },
};

export const FORM_SECTIONS: readonly FormSection[] = [
  {
    id: "screening",
    pillLabel: "Screening",
    title: "Are Micro-providers right for you?",
    description: "Before you use the tool we just want to ask as few questions to make sure Micro-providers are right for you. Because of the way that they operate most Micro-providers do not meet the criteria to be regulated by the Care Quality Commission (CQC). This does not mean they are unsafe or low quality.  It just means that they are only suitable for people who want control over who supports them, when and how.  These questions will help decide whether this is you or not.",
    items: [
      {
        kind: "radio",
        key: "completedBy",
        entryId: 1081703792,
        title: "Who is completing this form",
        required: true,
        options: [
          {
            label: "I am looking for support myself",
          },
          {
            label: "I am looking on behalf of a family member/ friend",
          },
          {
            label: "I work in Social Care / NHS",
          },
          {
            label: "I work in the voluntary, community or charity sector (VCSE)",
          },
        ],
      },
      {
        kind: "radio",
        key: "confirmConsent",
        entryId: 603369162,
        title: "I confirm that the individual requiring support has provided their consent for me to submit this referral.",
        required: true,
        options: [
          {
            label: "Yes",
          },
          {
            label: "No",
          },
        ],
      },
      {
        kind: "radio",
        key: "confirmAssess",
        entryId: 2043666850,
        title: "I confirm the person receiving support or their legal representative, is willing and able to assess the suitability of a micro-provider\nWhilst accredited by Somerset County Council,  Micro-providers have not had the checks that CQC regulated providers have. The person being cared for or their legal representative will need to interview potential providers, check their service portfolio and make a decision whether they are a good fit. Are they happy to do this?",
        required: true,
        options: [
          {
            label: "Yes",
          },
          {
            label: "No",
          },
        ],
      },
      {
        kind: "radio",
        key: "confirmCoordinate",
        entryId: 210863801,
        title: "I confirm the person receiving support or their legal representative, is willing and able to co-ordinate and manage their care on an ongoing basis.\nUsing a Micro-provider puts the person receiving care in full control. This often gives flexibility and a personalised experience of care. Sometimes people need more than one Micro-provider to cover different tasks and ensure they have support at different times. However, this means that the family are responsible for finding, interviewing, assessing suitability, and managing the activities of any Micro-provider/s. Are they willing and able to take on this level of responsibility?",
        required: true,
        options: [
          {
            label: "Yes",
          },
          {
            label: "No",
          },
        ],
      },
      {
        kind: "radio",
        key: "confirmCommunicate",
        entryId: 1788010623,
        title: "I confirm the person receiving support or their legal representative, is willing and able to communicate what they need, when they need it.\nBeing unregulated means Micro-providers are unable to direct, co-ordinate or manage care. Micro-providers will need to take their direction from the person receiving care or their legal representative, are they happy to do this?",
        required: true,
        options: [
          {
            label: "Yes",
          },
          {
            label: "No",
          },
        ],
      },
    ],
  },
  {
    id: "needs",
    pillLabel: "Your needs",
    title: "Your support needs",
    description: "Great news! It sounds like a Micro-provider could be the right option for you!",
    items: [
      {
        kind: "checkboxes",
        key: "services",
        entryId: 1895565538,
        title: "What type of support are you looking for?",
        required: false,
        options: [
          {
            label: "Personal Care",
          },
          {
            label: "Social and Community Support",
          },
          {
            label: "Help in the Home or Garden",
          },
          {
            label: "",
            isOther: true,
          },
        ],
      },
      {
        kind: "checkboxes",
        key: "funding",
        entryId: 532904551,
        title: "How will your care and support be funded?",
        required: false,
        options: [
          {
            label: "I will be funding my care and support with my own money",
          },
          {
            label: "The council are paying for my care and support (Direct Payments)",
          },
          {
            label: "The NHS are paying for my care and support (Personal Health Budget)",
          },
        ],
      },
    ],
  },
  {
    id: "about",
    pillLabel: "About you",
    title: "About you and the support you require:",
    items: [
      {
        kind: "short",
        key: "name",
        entryId: 1029857308,
        title: "Your name",
        required: true,
      },
      {
        kind: "short",
        key: "email",
        entryId: 30066852,
        title: "Email address",
        description: "*Please make sure your email is accurate, so we can contact you with local care options. Only enter an actual email address within this field, do not type any other text, for example, (this is my work email)\nTyping anything other than just an email address will cause the brokerage tool to fail and your care request will be unsuccessful.",
        required: true,
      },
      {
        kind: "short",
        key: "phone",
        entryId: 284650542,
        title: "Phone number",
        description: "This information will not be shared with Microproviders",
        required: true,
      },
      {
        kind: "paragraph",
        key: "headline",
        entryId: 1791923969,
        title: "Give your request for support a headline that summarises the support required. Think along the lines of a recruitment ad – this helps find someone compatible and attracts a more interest from Micro-providers.",
        description: "For example, ‘Wellington-based former-teacher and nature enthusiast, 82, looking for help around the home’\nPlease keep this support headline limited to 1 sentence (255 characters or less)",
        required: true,
        maxLength: 255,
      },
      {
        kind: "short",
        key: "locality",
        entryId: 17717468,
        title: "Please enter the town or village where support is required",
        description: "Please do not include your exact address",
        required: true,
      },
      {
        kind: "paragraph",
        key: "personSought",
        entryId: 948387899,
        title: "Is there a particular type of person or service you are looking for?\nFor example, are there any specific skills or experience needed? Do you have a preference for values, skills, and background? You might be looking for someone very bubbly and outgoing with experience in moving and handling, or perhaps someone very calm and patient with experience in dementia. This is your opportunity to specify the skills and attributes you need.",
        required: true,
      },
      {
        kind: "paragraph",
        key: "circumstances",
        entryId: 1922750044,
        title: "Please tell us anything else you would like to share about your situation and circumstances. This extra information will help match you to the right person.",
        description: "To help providers come back to you any ideas on times or Helpful information could include:\n\n- Task you would like the micro provider to complete\n- Medical condition (if you are comfortable to share)\n- Are you looking to build a care team or looking for an individual Micro-provider\n- A little bit about yourself, your interests and what a good life means to you!",
        required: true,
      },
      {
        kind: "radio",
        key: "pets",
        entryId: 2021225176,
        title: "Are there any pets in the house?",
        required: true,
        options: [
          {
            label: "Yes - please indicate  how many and what sort?",
          },
          {
            label: "No",
          },
        ],
      },
      {
        kind: "paragraph",
        key: "petDetails",
        entryId: 1474972490,
        title: "Please give details of any pets",
        required: false,
      },
      {
        kind: "paragraph",
        key: "schedule",
        entryId: 1679165166,
        title: "Days/Times/Hours\nPlease provide information on how many days in the week you would like help\n- Specific days and times\n- How long is required for each visit",
        required: true,
      },
    ],
  },
  {
    id: "consent",
    pillLabel: "Consent",
    title: "Information sharing consent",
    description: "To help us identify suitable micro-providers, we may need to share some non-personal information you have provided (for example, the type of support needed or general availability).\nWe will not share personal details such as your name, contact details, or address without your explicit permission.\nPlease tell us what you are happy for us to do:",
    items: [
      {
        kind: "radio",
        key: "consentWcn",
        entryId: 311722699,
        title: "I consent to some of the non-personal information provided above being shared with micro-providers registered with Wells Community Network.",
        required: true,
        options: [
          {
            label: "Yes",
          },
          {
            label: "No",
          },
        ],
      },
      {
        kind: "radio",
        key: "consentOther",
        entryId: 1600711344,
        title: "I consent to some of the non-personal information provided above being shared with micro-providers registered with other micro-provider networks.",
        required: true,
        options: [
          {
            label: "Yes",
          },
          {
            label: "No",
          },
        ],
      },
      {
        kind: "note",
        title: "You can change or withdraw your consent at any time by contacting Wells Community Network.",
        description: "email wcnmicroproviders@gmail.com or telephone the WCN Helpline 01749 467079.",
      },
    ],
  },
  {
    id: "touch",
    pillLabel: "Staying in touch",
    title: "Staying in Touch",
    items: [
      {
        kind: "radio",
        key: "heardAbout",
        entryId: 1423090436,
        title: "How did you hear about Wells Community Network Microproviders?",
        required: true,
        options: [
          {
            label: "WCN Website",
          },
          {
            label: "Google search",
          },
          {
            label: "WCN Advert",
          },
          {
            label: "WCN Helpline",
          },
          {
            label: "Social media",
          },
          {
            label: "Friend or family member",
          },
          {
            label: "Health or social care professional",
          },
          {
            label: "Another organisation",
          },
          {
            label: "Somerset Council brokerage tool",
          },
          {
            label: "Events",
          },
          {
            label: "",
            isOther: true,
          },
        ],
      },
      {
        kind: "radio",
        key: "newsletter",
        entryId: 577778576,
        title: "Would you like to receive the WCN Newsletter?",
        description: "The fortnightly newsletter shares updates about WCN’s work, local support, and positive community news.\nYou can unsubscribe at any time.",
        required: true,
        options: [
          {
            label: "Yes, please",
          },
          {
            label: "No, thank you",
          },
        ],
      },
    ],
  },
  {
    id: "disclaimer",
    pillLabel: "Disclaimer",
    title: "Disclaimer",
    description: "Wells Community Network provides information and signposting to independent microproviders as a community support service. We are not a brokerage, commissioning, or referral service and do not assess, recommend, endorse, employ, or monitor any provider listed or signposted.\nAny decision to contact or engage a provider is made entirely at the individual’s or family’s own discretion. We strongly encourage individuals and families to carry out their own checks, including suitability, qualifications, references, safeguarding arrangements, insurance, and any relevant regulatory requirements, before entering into any agreement.\nWells Community Network accepts no responsibility or liability for the actions, services, or conduct of any third-party provider.",
    items: [
      {
        kind: "checkboxes",
        key: "disclaimerRead",
        entryId: 1550210671,
        title: "I confirm that I have read and understood this disclaimer",
        required: true,
        options: [
          {
            label: "I have read and understood the disclaimer",
          },
        ],
      },
      {
        kind: "checkboxes",
        key: "accurateInfo",
        entryId: 86681631,
        title: "I confirm that the information I have provided is accurate to the best of my knowledge and that I have read and understood the information provided.",
        required: true,
        options: [
          {
            label: "I confirm that the information is accurate",
          },
        ],
      },
    ],
  },
];

/** Compile-time drift guards: the build fails if the live form's option
 *  labels stop matching the canonical arrays in ./types. */
export const OPTION_DRIFT_GUARDS = {
  services: ["Personal Care", "Social and Community Support", "Help in the Home or Garden"] as const satisfies typeof SERVICES,
  funding: ["I will be funding my care and support with my own money", "The council are paying for my care and support (Direct Payments)", "The NHS are paying for my care and support (Personal Health Budget)"] as const satisfies typeof FUNDING_OPTIONS,
  completedBy: ["I am looking for support myself", "I am looking on behalf of a family member/ friend", "I work in Social Care / NHS", "I work in the voluntary, community or charity sector (VCSE)"] as const satisfies typeof COMPLETED_BY_OPTIONS,
  heardAbout: ["WCN Website", "Google search", "WCN Advert", "WCN Helpline", "Social media", "Friend or family member", "Health or social care professional", "Another organisation", "Somerset Council brokerage tool", "Events"] as const satisfies typeof HEARD_ABOUT_OPTIONS,
};
