import type { Client, MicroProvider, SupportRequest, Volunteer } from "./types";

// Every person below is fictional. Phone numbers use the Ofcom-reserved
// drama range (01632 960xxx), emails use example.org and postcodes use
// unused ZZ-style inward codes, so no sample detail can ever reach a real
// person. Core training uses the canonical names in lib/training.ts.

export const seedProviders: MicroProvider[] = [
  {
    id: "mp-01",
    name: "Sarah Treloar",
    locality: "Wells",
    outwardPostcode: "BA5",
    postCode: "BA5 1ZZ",
    areasCovered: ["Wells", "Wookey", "Coxley", "Dulcote"],
    dateOfBirth: "1962-07-04",
    services: ["Personal Care", "Social and Community Support"],
    bio: "Former district nurse offering personal care with a friendly, unhurried visit — happy to combine calls with a walk or errands.",
    availability: "Weekday mornings · up to 8 hrs/week",
    email: "sarah.treloar@example.org",
    phone: "01632 960101",
    startDate: "2022-04-11",
    dbsNumber: "001565842291",
    dbsExpiry: "2027-04-10",
    publicLiabilityNumber: "PL-1029384",
    publicLiabilityExpiry: "2027-02-01",
    feePaymentDate: "2026-01-15",
    training: [
      { name: "Moving & Handling", completed: "2025-09-14", expiry: "2026-09-14" },
      { name: "Safeguarding Adults", completed: "2025-05-02", expiry: "2027-05-02" },
      { name: "Emergency First Aid", completed: "2024-11-20", expiry: "2027-11-20" },
    ],
  },
  {
    id: "mp-02",
    name: "Martin Hobbs",
    locality: "Shepton Mallet",
    outwardPostcode: "BA4",
    postCode: "BA4 1ZZ",
    areasCovered: ["Shepton Mallet", "Croscombe", "Pilton", "North Wootton"],
    dateOfBirth: "1958-11-19",
    services: ["Help in the Home or Garden"],
    bio: "Retired builder for odd jobs, gardens and small adaptations — grab rails, ramps, overgrown borders. No job too small.",
    availability: "Tue–Sat · flexible",
    email: "martin.hobbs@example.org",
    phone: "01632 960102",
    startDate: "2023-01-30",
    dbsNumber: "001598263107",
    dbsExpiry: "2026-08-28",
    publicLiabilityNumber: "PL-2214379",
    publicLiabilityExpiry: "2027-06-15",
    feePaymentDate: "2026-02-01",
    training: [
      { name: "Safeguarding Adults", completed: "2025-08-28", expiry: "2026-08-28" },
      { name: "Ladder & Working at Height", completed: "2025-03-10", expiry: "2028-03-10" },
    ],
  },
  {
    id: "mp-03",
    name: "Priya Nair",
    locality: "Wells",
    outwardPostcode: "BA5",
    postCode: "BA5 2ZZ",
    areasCovered: ["All"],
    dateOfBirth: "1979-02-25",
    services: ["Personal Care"],
    bio: "Calm and patient carer with twelve years of dementia experience; comfortable with hoists and all moving-and-handling.",
    availability: "Weekdays incl. evenings · 12 hrs/week free",
    email: "priya.nair@example.org",
    phone: "01632 960103",
    startDate: "2021-09-06",
    dbsNumber: "001611472850",
    dbsExpiry: "2027-09-05",
    publicLiabilityNumber: "PL-3306415",
    publicLiabilityExpiry: "2027-01-12",
    feePaymentDate: "2026-03-09",
    training: [
      { name: "Moving & Handling", completed: "2026-01-19", expiry: "2027-01-19" },
      { name: "Emergency First Aid", completed: "2025-03-15", expiry: "2027-03-15" },
      { name: "Dementia Awareness", completed: "2025-06-30", expiry: "2028-06-30" },
      { name: "Medication Awareness", completed: "2025-10-08", expiry: "2026-10-08" },
    ],
  },
  {
    id: "mp-04",
    name: "Deb & Ian Coombes",
    locality: "Croscombe",
    outwardPostcode: "BA5",
    postCode: "BA5 3ZZ",
    areasCovered: ["All"],
    services: ["Social and Community Support", "Help in the Home or Garden"],
    bio: "Husband-and-wife team for lifts to clubs, shopping and appointments, plus housework and garden upkeep between visits.",
    availability: "Mon–Fri daytime · car with wheelchair space",
    email: "coombes.support@example.org",
    phone: "01632 960104",
    startDate: "2023-06-19",
    dbsNumber: "001624901738",
    dbsExpiry: "2027-06-18",
    publicLiabilityNumber: "PL-4418293",
    publicLiabilityExpiry: "2026-10-05",
    feePaymentDate: "2026-04-22",
    training: [
      { name: "Safeguarding Adults", completed: "2026-04-22", expiry: "2027-04-22" },
      { name: "Passenger Assistance", completed: "2025-07-01", expiry: "2027-07-01" },
    ],
  },
  {
    id: "mp-05",
    name: "Grace Adeyemi",
    locality: "Westbury-sub-Mendip",
    outwardPostcode: "BA5",
    postCode: "BA5 4ZZ",
    areasCovered: [
      "Westbury-sub-Mendip",
      "Wells",
      "Wookey",
      "Wookey Hole",
      "Easton",
      "Priddy",
    ],
    dateOfBirth: "1985-09-12",
    services: ["Personal Care", "Social and Community Support"],
    bio: "Overnight and respite specialist — steady support so families can rest, with warm company through the evening routine.",
    availability: "Overnights & weekends",
    email: "grace.adeyemi@example.org",
    phone: "01632 960105",
    startDate: "2024-02-12",
    dbsNumber: "001637265014",
    dbsExpiry: "2028-02-11",
    publicLiabilityNumber: "PL-5521067",
    publicLiabilityExpiry: "2027-03-20",
    feePaymentDate: "2026-02-12",
    training: [
      { name: "Moving & Handling", completed: "2025-11-11", expiry: "2026-11-11" },
      { name: "Safeguarding Adults", completed: "2025-11-11", expiry: "2027-11-11" },
    ],
  },
  {
    id: "mp-06",
    name: "Tom Vickery",
    locality: "Wookey",
    outwardPostcode: "BA5",
    postCode: "BA5 5ZZ",
    areasCovered: [
      "Wookey",
      "Wookey Hole",
      "Wells",
      "Westbury-sub-Mendip",
      "Coxley",
      "Easton",
    ],
    dateOfBirth: "1969-05-30",
    services: ["Help in the Home or Garden"],
    bio: "Ex-firefighter focused on safe homes: decluttering, smoke alarms, trip hazards, seasonal garden tidy-ups.",
    availability: "Weekdays · mornings preferred",
    email: "tom.vickery@example.org",
    phone: "01632 960106",
    startDate: "2022-10-03",
    dbsNumber: "001649822476",
    dbsExpiry: "2026-11-02",
    publicLiabilityNumber: "PL-6633148",
    publicLiabilityExpiry: "2027-05-09",
    feePaymentDate: "2026-05-19",
    training: [
      { name: "Home Fire Safety", completed: "2024-09-15", expiry: "2027-09-15" },
      { name: "Safeguarding Adults", completed: "2025-12-01", expiry: "2026-12-01" },
    ],
  },
  {
    id: "mp-07",
    name: "Eleanor Fitch",
    locality: "Shepton Mallet",
    outwardPostcode: "BA4",
    postCode: "BA4 2ZZ",
    areasCovered: [
      "Shepton Mallet",
      "Pilton",
      "Croscombe",
      "Dinder",
      "North Wootton",
    ],
    dateOfBirth: "1990-12-08",
    services: ["Social and Community Support"],
    bio: "Bubbly companionship visits — crosswords, memory café trips, a proper natter; runs a small Thursday walking group.",
    availability: "Mon, Wed, Thu · afternoons",
    email: "eleanor.fitch@example.org",
    phone: "01632 960107",
    startDate: "2024-05-27",
    dbsNumber: "001652390841",
    dbsExpiry: "2027-05-26",
    publicLiabilityNumber: "PL-7745920",
    publicLiabilityExpiry: "2026-12-14",
    feePaymentDate: "2026-06-02",
    training: [
      { name: "Safeguarding Adults", completed: "2026-05-27", expiry: "2027-05-27" },
      { name: "Dementia Friends", completed: "2024-06-10", expiry: "2027-06-10" },
    ],
  },
  {
    id: "mp-08",
    name: "Josh Parkin",
    locality: "North Wootton",
    outwardPostcode: "BA4",
    postCode: "BA4 3ZZ",
    areasCovered: [
      "North Wootton",
      "Pilton",
      "Shepton Mallet",
      "Croscombe",
      "Dinder",
      "Dulcote",
    ],
    dateOfBirth: "1988-03-17",
    services: ["Personal Care", "Help in the Home or Garden"],
    bio: "Strong, practical support — full moving-and-handling training plus the muscle for log stores, lofts and heavy garden work.",
    availability: "Limited — 4 hrs/week until September",
    email: "josh.parkin@example.org",
    phone: "01632 960108",
    startDate: "2023-11-13",
    dbsNumber: "001664758203",
    dbsExpiry: "2027-11-12",
    publicLiabilityNumber: "PL-8852761",
    publicLiabilityExpiry: "2026-06-30",
    feePaymentDate: "unpaid",
    training: [
      { name: "Moving & Handling", completed: "2025-10-30", expiry: "2026-10-30" },
      { name: "Safeguarding Adults", completed: "2025-08-14", expiry: "2026-08-14" },
    ],
  },
];

export const seedClients: Client[] = [
  {
    id: "c-01",
    customId: "WCN-0102",
    name: "Margaret Holloway",
    dateOfBirth: "1942-03-08",
    locality: "Wells",
    postCode: "BA5 6ZZ",
    services: ["Personal Care"],
    funding: ["The council are paying for my care and support (Direct Payments)"],
    onboarded: "2026-02-09",
    status: "Matched",
    attendanceAllowance: "High",
    headline: "Wells resident, 84, needs gentle morning routine support after a hip operation",
  },
  {
    id: "c-02",
    customId: "WCN-0117",
    name: "Ronald Peters",
    dateOfBirth: "1947-06-21",
    locality: "Shepton Mallet",
    postCode: "BA4 4ZZ",
    services: ["Help in the Home or Garden"],
    funding: ["I will be funding my care and support with my own money"],
    onboarded: "2026-03-21",
    status: "Matched",
    attendanceAllowance: "None",
    deprivation: { income: true, health: false },
    headline: "Keen gardener, 79, wants a hand keeping the vegetable patch going",
  },
  {
    id: "c-03",
    customId: "WCN-0129",
    name: "June & Alfred Tinney",
    locality: "Croscombe",
    postCode: "BA5 7ZZ",
    services: ["Social and Community Support", "Help in the Home or Garden"],
    funding: ["I will be funding my care and support with my own money"],
    onboarded: "2026-04-14",
    status: "Active",
    attendanceAllowance: "Pending",
    headline: "Couple in Croscombe looking for lifts to clubs and light housework",
  },
  {
    id: "c-04",
    customId: "WCN-0136",
    name: "Dorothy Sampson",
    dateOfBirth: "1938-01-27",
    locality: "Wookey",
    postCode: "BA5 8ZZ",
    services: ["Social and Community Support"],
    funding: ["The council are paying for my care and support (Direct Payments)"],
    onboarded: "2026-05-02",
    status: "Active",
    attendanceAllowance: "Low",
    deprivation: { income: false, health: true },
    headline: "Former teacher, 88, would love company for crosswords and short walks",
  },
  {
    id: "c-05",
    customId: "WCN-0150",
    name: "Bill Hartnell",
    dateOfBirth: "1935-04-02",
    locality: "Westbury-sub-Mendip",
    postCode: "BA5 9ZZ",
    services: ["Personal Care", "Social and Community Support"],
    funding: [
      "The NHS are paying for my care and support (Personal Health Budget)",
    ],
    onboarded: "2026-06-11",
    status: "Active",
    attendanceAllowance: "High",
    headline: "Veteran, 91, needs evening check-ins and help with supper",
  },
  {
    id: "c-06",
    customId: "WCN-0163",
    name: "Iris Quick",
    dateOfBirth: "1950-05-11",
    locality: "Pilton",
    postCode: "BA4 5ZZ",
    services: ["Help in the Home or Garden"],
    funding: ["I will be funding my care and support with my own money"],
    onboarded: "2026-07-01",
    status: "New request",
    attendanceAllowance: "Unsent",
    headline: "Pilton smallholder, 76, after help with the orchard and log store",
  },
];

export const seedVolunteers: Volunteer[] = [
  {
    id: "v-01",
    name: "Angela Frost",
    role: "Helpline volunteer",
    dateOfBirth: "1954-10-05",
    locality: "Wells",
    postCode: "BA5 0ZZ",
    email: "angela.frost@example.org",
    phone: "01632 960201",
    since: "2021-03-15",
    dbsNumber: "001573619402",
    dbsExpiry: "2027-03-14",
    training: [
      { name: "Safeguarding Adults", completed: "2026-03-01", expiry: "2027-03-01" },
      { name: "Emergency First Aid", completed: "2025-08-05", expiry: "2026-08-05" },
    ],
  },
  {
    id: "v-02",
    name: "Colin Drury",
    role: "Micro-provider liaison",
    dateOfBirth: "1948-02-14",
    locality: "Shepton Mallet",
    postCode: "BA4 6ZZ",
    email: "colin.drury@example.org",
    phone: "01632 960202",
    since: "2022-08-01",
    dbsNumber: "001586104738",
    dbsExpiry: "2026-09-18",
    publicLiabilityNumber: "PL-9910384",
    publicLiabilityExpiry: "2026-09-30",
    training: [
      { name: "Safeguarding Adults", completed: "2025-10-12", expiry: "2026-10-12" },
    ],
  },
  {
    id: "v-03",
    name: "Beth Osman",
    role: "Newsletter & events",
    dateOfBirth: "1996-06-30",
    locality: "Dinder",
    postCode: "BA5 1ZY",
    email: "beth.osman@example.org",
    phone: "01632 960203",
    since: "2024-01-22",
    dbsNumber: "001593827460",
    dbsExpiry: "2028-01-21",
    training: [
      { name: "Safeguarding Adults", completed: "2025-08-20", expiry: "2027-08-20" },
    ],
  },
];

// Iris Quick's open request (client c-06, status "New request"), so the
// dashboard and results view have content before anyone uses the form.
export const seedRequests: SupportRequest[] = [
  {
    id: "req-01",
    createdAt: "2026-07-01T10:24:00Z",
    clientId: "c-06",
    completedBy: "I am looking for support myself",
    services: ["Help in the Home or Garden"],
    funding: ["I will be funding my care and support with my own money"],
    name: "Iris Quick",
    email: "iris.quick@example.org",
    phone: "01632 960301",
    headline: "Pilton smallholder, 76, after help with the orchard and log store",
    locality: "Pilton",
    personSought: "Someone practical and local who doesn't mind proper outdoor work",
    circumstances:
      "Managing well in the farmhouse, but the orchard, log store and heavier garden jobs have got beyond me since last winter.",
    hasPets: true,
    petDetails: "Two cats and a dozen hens",
    schedule: "Weekday mornings, flexible",
    consentWcnNetwork: true,
    consentOtherNetworks: false,
    heardAbout: "WCN Helpline",
    newsletter: false,
  },
];
