import type { Client, MicroProvider, Volunteer } from "./types";

// Every person below is fictional. Phone numbers use the Ofcom-reserved
// drama range (01632 960xxx) and emails use example.org, so no sample
// detail can ever reach a real person.

export const seedProviders: MicroProvider[] = [
  {
    id: "mp-01",
    name: "Sarah Treloar",
    locality: "Wells",
    outwardPostcode: "BA5",
    services: ["Personal Care", "Social and Community Support"],
    bio: "Former district nurse offering personal care with a friendly, unhurried visit — happy to combine calls with a walk or errands.",
    availability: "Weekday mornings · up to 8 hrs/week",
    email: "sarah.treloar@example.org",
    phone: "01632 960101",
    startDate: "2022-04-11",
    dbsExpiry: "2027-04-10",
    liabilityExpiry: "2027-02-01",
    training: [
      { name: "Moving & Handling", completed: "2025-09-14", expiry: "2026-09-14" },
      { name: "Safeguarding Adults L2", completed: "2025-05-02", expiry: "2027-05-02" },
      { name: "Emergency First Aid", completed: "2024-11-20", expiry: "2027-11-20" },
    ],
  },
  {
    id: "mp-02",
    name: "Martin Hobbs",
    locality: "Shepton Mallet",
    outwardPostcode: "BA4",
    services: ["Help in the Home or Garden"],
    bio: "Retired builder for odd jobs, gardens and small adaptations — grab rails, ramps, overgrown borders. No job too small.",
    availability: "Tue–Sat · flexible",
    email: "martin.hobbs@example.org",
    phone: "01632 960102",
    startDate: "2023-01-30",
    dbsExpiry: "2026-08-28",
    liabilityExpiry: "2027-06-15",
    training: [
      { name: "Safeguarding Adults L1", completed: "2025-08-28", expiry: "2026-08-28" },
      { name: "Ladder & Working at Height", completed: "2025-03-10", expiry: "2028-03-10" },
    ],
  },
  {
    id: "mp-03",
    name: "Priya Nair",
    locality: "Wells",
    outwardPostcode: "BA5",
    services: ["Personal Care"],
    bio: "Calm and patient carer with twelve years of dementia experience; comfortable with hoists and all moving-and-handling.",
    availability: "Weekdays incl. evenings · 12 hrs/week free",
    email: "priya.nair@example.org",
    phone: "01632 960103",
    startDate: "2021-09-06",
    dbsExpiry: "2027-09-05",
    liabilityExpiry: "2027-01-12",
    training: [
      { name: "Moving & Handling (incl. hoists)", completed: "2026-01-19", expiry: "2027-01-19" },
      { name: "Dementia Awareness", completed: "2025-06-30", expiry: "2028-06-30" },
      { name: "Medication Awareness", completed: "2025-10-08", expiry: "2026-10-08" },
    ],
  },
  {
    id: "mp-04",
    name: "Deb & Ian Coombes",
    locality: "Croscombe",
    outwardPostcode: "BA5",
    services: ["Social and Community Support", "Help in the Home or Garden"],
    bio: "Husband-and-wife team for lifts to clubs, shopping and appointments, plus housework and garden upkeep between visits.",
    availability: "Mon–Fri daytime · car with wheelchair space",
    email: "coombes.support@example.org",
    phone: "01632 960104",
    startDate: "2023-06-19",
    dbsExpiry: "2027-06-18",
    liabilityExpiry: "2026-10-05",
    training: [
      { name: "Safeguarding Adults L1", completed: "2025-04-22", expiry: "2026-04-22" },
      { name: "Passenger Assistance", completed: "2025-07-01", expiry: "2027-07-01" },
    ],
  },
  {
    id: "mp-05",
    name: "Grace Adeyemi",
    locality: "Westbury-sub-Mendip",
    outwardPostcode: "BA5",
    services: ["Personal Care", "Social and Community Support"],
    bio: "Overnight and respite specialist — steady support so families can rest, with warm company through the evening routine.",
    availability: "Overnights & weekends",
    email: "grace.adeyemi@example.org",
    phone: "01632 960105",
    startDate: "2024-02-12",
    dbsExpiry: "2028-02-11",
    liabilityExpiry: "2027-03-20",
    training: [
      { name: "Moving & Handling", completed: "2025-11-11", expiry: "2026-11-11" },
      { name: "Safeguarding Adults L2", completed: "2025-11-11", expiry: "2027-11-11" },
    ],
  },
  {
    id: "mp-06",
    name: "Tom Vickery",
    locality: "Wookey",
    outwardPostcode: "BA5",
    services: ["Help in the Home or Garden"],
    bio: "Ex-firefighter focused on safe homes: decluttering, smoke alarms, trip hazards, seasonal garden tidy-ups.",
    availability: "Weekdays · mornings preferred",
    email: "tom.vickery@example.org",
    phone: "01632 960106",
    startDate: "2022-10-03",
    dbsExpiry: "2026-11-02",
    liabilityExpiry: "2027-05-09",
    training: [
      { name: "Home Fire Safety", completed: "2024-09-15", expiry: "2027-09-15" },
      { name: "Safeguarding Adults L1", completed: "2025-12-01", expiry: "2026-12-01" },
    ],
  },
  {
    id: "mp-07",
    name: "Eleanor Fitch",
    locality: "Shepton Mallet",
    outwardPostcode: "BA4",
    services: ["Social and Community Support"],
    bio: "Bubbly companionship visits — crosswords, memory café trips, a proper natter; runs a small Thursday walking group.",
    availability: "Mon, Wed, Thu · afternoons",
    email: "eleanor.fitch@example.org",
    phone: "01632 960107",
    startDate: "2024-05-27",
    dbsExpiry: "2027-05-26",
    liabilityExpiry: "2026-12-14",
    training: [
      { name: "Safeguarding Adults L1", completed: "2025-05-27", expiry: "2026-05-27" },
      { name: "Dementia Friends", completed: "2024-06-10", expiry: "2027-06-10" },
    ],
  },
  {
    id: "mp-08",
    name: "Josh Parkin",
    locality: "North Wootton",
    outwardPostcode: "BA4",
    services: ["Personal Care", "Help in the Home or Garden"],
    bio: "Strong, practical support — full moving-and-handling training plus the muscle for log stores, lofts and heavy garden work.",
    availability: "Limited — 4 hrs/week until September",
    email: "josh.parkin@example.org",
    phone: "01632 960108",
    startDate: "2023-11-13",
    dbsExpiry: "2027-11-12",
    liabilityExpiry: "2026-06-30",
    training: [
      { name: "Moving & Handling", completed: "2025-10-30", expiry: "2026-10-30" },
      { name: "Safeguarding Adults L1", completed: "2025-02-14", expiry: "2026-02-14" },
    ],
  },
];

export const seedClients: Client[] = [
  {
    id: "c-01",
    name: "Margaret Holloway",
    locality: "Wells",
    services: ["Personal Care"],
    onboarded: "2026-02-09",
    status: "Matched",
    headline: "Wells resident, 84, needs gentle morning routine support after a hip operation",
  },
  {
    id: "c-02",
    name: "Ronald Peters",
    locality: "Shepton Mallet",
    services: ["Help in the Home or Garden"],
    onboarded: "2026-03-21",
    status: "Matched",
    headline: "Keen gardener, 79, wants a hand keeping the vegetable patch going",
  },
  {
    id: "c-03",
    name: "June & Alfred Tinney",
    locality: "Croscombe",
    services: ["Social and Community Support", "Help in the Home or Garden"],
    onboarded: "2026-04-14",
    status: "Active",
    headline: "Couple in Croscombe looking for lifts to clubs and light housework",
  },
  {
    id: "c-04",
    name: "Dorothy Sampson",
    locality: "Wookey",
    services: ["Social and Community Support"],
    onboarded: "2026-05-02",
    status: "Active",
    headline: "Former teacher, 88, would love company for crosswords and short walks",
  },
  {
    id: "c-05",
    name: "Bill Hartnell",
    locality: "Westbury-sub-Mendip",
    services: ["Personal Care", "Social and Community Support"],
    onboarded: "2026-06-11",
    status: "Active",
    headline: "Veteran, 91, needs evening check-ins and help with supper",
  },
  {
    id: "c-06",
    name: "Iris Quick",
    locality: "Pilton",
    services: ["Help in the Home or Garden"],
    onboarded: "2026-07-01",
    status: "New request",
    headline: "Pilton smallholder, 76, after help with the orchard and log store",
  },
];

export const seedVolunteers: Volunteer[] = [
  {
    id: "v-01",
    name: "Angela Frost",
    role: "Helpline volunteer",
    locality: "Wells",
    email: "angela.frost@example.org",
    phone: "01632 960201",
    since: "2021-03-15",
    dbsExpiry: "2027-03-14",
  },
  {
    id: "v-02",
    name: "Colin Drury",
    role: "Micro-provider liaison",
    locality: "Shepton Mallet",
    email: "colin.drury@example.org",
    phone: "01632 960202",
    since: "2022-08-01",
    dbsExpiry: "2026-09-18",
  },
  {
    id: "v-03",
    name: "Beth Osman",
    role: "Newsletter & events",
    locality: "Dinder",
    email: "beth.osman@example.org",
    phone: "01632 960203",
    since: "2024-01-22",
    dbsExpiry: "2028-01-21",
  },
];
